
import './globals.css';
import { AuthContextProvider } from './context/AuthContext';
import Navbar from './components/Navbar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <Navbar />
          {children} 
        </AuthContextProvider>
      </body>
    </html>
  )
}
